"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, ChevronDown, ChevronRight, CircleDashed, FlaskConical, LockKeyhole, Terminal } from "lucide-react";
import type { EveAgentCatalog, EveEvalCatalogFile } from "@/lib/eve-agent-catalog";

type LabClientProps = { catalog: EveAgentCatalog | null };

function SetupState() {
  return <main className="min-h-dvh bg-[var(--ground-2)] p-6 text-[var(--ink)] md:p-10"><div className="mx-auto max-w-2xl rounded-2xl border border-[var(--rule)] bg-white p-8"><LockKeyhole className="size-5 text-[var(--ink-60)]" /><p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--ink-60)]">Laboratorio Eve</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-[-0.04em]">Configura el acceso de Ops</h1><p className="mt-3 text-sm leading-6 text-[var(--ink-60)]">Esta vista requiere la sesión de operador y solo muestra archivos de evaluación reales.</p></div></main>;
}

function EvalRow({ evaluation }: { evaluation: EveEvalCatalogFile }) {
  const [open, setOpen] = useState(false);
  return <div className="rounded-xl border border-[var(--hairline)] bg-white"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} className="flex min-h-[76px] w-full items-center gap-3 px-4 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-inset focus-visible:outline-[var(--rule)]"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-[var(--ground-3)] text-[var(--ink-60)]"><CircleDashed className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[var(--ink)]">{evaluation.label}</span><span className="mt-1 block truncate text-xs text-[var(--ink-60)]">{evaluation.description}</span></span>{evaluation.usesJudge && <span className="hidden rounded-full bg-[var(--warn-soft)] px-2 py-1 text-[10px] font-medium text-[var(--status-warn)] sm:inline-flex">LLM judge</span>}{open ? <ChevronDown className="size-4 shrink-0 text-[var(--ink-60)]" /> : <ChevronRight className="size-4 shrink-0 text-[var(--ink-60)]" />}</button>{open && <div className="border-t border-[var(--hairline)] px-4 pb-4 pt-3 pl-[4.2rem]"><p className="text-xs leading-5 text-[var(--ink-60)]">{evaluation.description}</p><p className="mt-3 font-mono text-[10px] text-[var(--ink-40)]">{evaluation.sourcePath}</p><div className="mt-3 inline-flex items-center gap-1.5 text-xs font-medium text-[var(--assist-ink)]"><CheckCircle2 className="size-3.5" /> Descubierta, pendiente de ejecución</div></div>}</div>;
}

export default function LabClient({ catalog }: LabClientProps) {
  if (!catalog) return <SetupState />;

  return <main className="min-h-dvh bg-[var(--ground-2)] pb-12 text-[var(--ink)]"><div className="mx-auto w-full max-w-[1400px] px-4 py-7 sm:px-6 lg:px-9 lg:py-9"><header className="flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.16em] text-[var(--ink-60)]"><FlaskConical className="size-4 text-[var(--ink-60)]" /> Eve · Observabilidad</div><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Evalúa antes de promover</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--ink-60)]">Inventario verificable de evaluaciones y controles descubiertos por Eve. No muestra scores ni ejecuciones que no existan.</p></div><Link href="/ops/agents#crear-agente" className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-[var(--rule)] bg-white px-4 text-sm font-semibold text-[var(--ink-60)] shadow-[var(--shadow-sm)] transition hover:border-[var(--rule)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--rule)]">Gestionar Eve Agents <ArrowRight className="size-4" /></Link></header>

    <div className="mt-8 grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="space-y-5"><article className="rounded-2xl border border-[var(--rule)] bg-white p-5 shadow-[var(--shadow-md)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--ink-40)]">Estado del laboratorio</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] text-[var(--ink)]">Catálogo disponible</h2></div><span className="inline-flex items-center gap-2 rounded-full border border-[var(--assist-line)] bg-[var(--assist-soft)] px-3 py-1.5 text-xs font-medium text-[var(--assist-ink)]"><span className="size-1.5 rounded-full bg-[var(--assist)]" /> {catalog.evals.length} evals descubiertas</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[var(--hairline)] bg-[var(--ground-2)] p-4"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--ink-40)]">Definición</p><p className="mt-2 text-sm font-semibold text-[var(--ink)]">{catalog.evalConfig.discovered ? "Encontrada" : "No encontrada"}</p><p className="mt-1 text-xs text-[var(--ink-60)]">evals/evals.config.ts</p></div><div className="rounded-xl border border-[var(--hairline)] bg-[var(--ground-2)] p-4"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--ink-40)]">Judge</p><p className="mt-2 text-sm font-semibold text-[var(--ink)]">{catalog.evalConfig.usesJudge ? "Configurado" : "No configurado"}</p><p className="mt-1 text-xs text-[var(--ink-60)]">Se verifica al ejecutar Eve</p></div><div className="rounded-xl border border-[var(--hairline)] bg-[var(--ground-2)] p-4"><p className="text-[10px] uppercase tracking-[0.12em] text-[var(--ink-40)]">Resultado</p><p className="mt-2 text-sm font-semibold text-[var(--ink)]">Sin ejecución</p><p className="mt-1 text-xs text-[var(--ink-60)]">No se inventan scores</p></div></div></article>

      <article className="rounded-2xl border border-[var(--rule)] bg-white p-5 shadow-[var(--shadow-md)] sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--ink-40)]">Historial de evaluaciones</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em] text-[var(--ink)]">Casos descubiertos</h2></div><span className="text-xs text-[var(--ink-40)]">Fuente: apps/growth-agent/evals</span></div><div className="mt-5 space-y-2">{catalog.evals.length ? catalog.evals.map((evaluation) => <EvalRow key={evaluation.sourcePath} evaluation={evaluation} />) : <div className="rounded-xl border border-dashed border-[var(--rule)] p-8 text-center text-sm text-[var(--ink-60)]">No hay archivos `.eval.ts` en el repositorio.</div>}</div></article>

      <article className="rounded-2xl border border-[var(--assist-line)] bg-[var(--assist-soft)] p-5 sm:p-6"><div className="flex items-start gap-3"><span className="inline-flex size-9 shrink-0 items-center justify-center rounded-lg bg-white text-[var(--assist-ink)]"><Terminal className="size-4" /></span><div><h2 className="text-sm font-semibold text-[var(--ink)]">Ejecutar desde el entorno controlado</h2><p className="mt-2 text-xs leading-5 text-[var(--ink-60)]">La ejecución real debe ocurrir en el workspace de Eve, con sus credenciales y su servidor. El panel solo ofrece el comando verificable.</p><code className="on-ink mt-4 block overflow-x-auto rounded-lg bg-[var(--ink-fill)] px-3 py-3 font-mono text-[11px] text-[var(--assist-ink)]">cd apps/growth-agent &amp;&amp; pnpm eval --list</code><p className="mt-3 text-[11px] text-[var(--ink-60)]">Después, usa <code>pnpm eval --strict --junit .eve/junit.xml</code> en CI o en un entorno de evaluación explícito.</p></div></div></article>
    </section>

    <aside className="space-y-5"><article className="rounded-2xl border border-[var(--rule)] bg-white p-5 shadow-[var(--shadow-md)]"><h2 className="text-sm font-semibold text-[var(--ink)]">Qué valida este catálogo</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-[var(--ink-60)]"><li className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--assist-ink)]" /> Que el agente complete la tarea esperada.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--assist-ink)]" /> Que respete límites de outreach y aprobación.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--assist-ink)]" /> Que no persista datos personales sin base pública.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[var(--assist-ink)]" /> Que la evidencia comercial tenga una URL verificable.</li></ul></article><article className="rounded-2xl border border-[var(--warn-line)] bg-[var(--warn-soft)] p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-[var(--status-warn)]" /><div><h2 className="text-sm font-semibold text-[var(--status-warn)]">Ejecuciones aún no integradas</h2><p className="mt-2 text-xs leading-5 text-[var(--status-warn)]">El panel muestra sólo observabilidad disponible. El historial real aparecerá cuando Eve exponga sus artefactos `.eve/`; hasta entonces no se inventan estados ni scores.</p></div></div></article><article className="rounded-2xl border border-[var(--rule)] bg-white p-5 shadow-[var(--shadow-md)]"><h2 className="text-sm font-semibold text-[var(--ink)]">Flujo recomendado</h2><ol className="mt-4 space-y-3">{["Edita instrucciones y tools en una rama", "Ejecuta evals con modelos de prueba", "Revisa artefactos y gates", "Promueve a Approval antes de producción"].map((step, index) => <li key={step} className="flex items-start gap-3 text-xs leading-5 text-[var(--ink-60)]"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-[var(--ground-3)] text-[10px] font-semibold text-[var(--ink-60)]">{index + 1}</span>{step}</li>)}</ol></article></aside></div>
  </div></main>;
}
